/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectPanel.java
 *
 * Created on 15.Ara.2011, 12:32:15
 */
package GUI;

import Component.Project;
import java.awt.Graphics;
import javax.swing.JButton;

/**
 *
 * @author ok@n
 */
public class ProjectPanel extends javax.swing.JPanel {

    
    static Project project = null;
    JButton b;
    
    public static Project getProject(){
        if(project==null){
            project = new Project();
        }
        return project;
    }
    
    /** Creates new form ProjectPanel */
    public ProjectPanel(String projectName) {
        super();
        initComponents();
        project = new Project(projectName);
        project.getRoot().setLocation(50, DrawPanel.getWidth()/2);
        DrawPanel.add(project.getRoot());
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        //project.getRoot().paint(DrawPanel.getGraphics());
        //b.paint(DrawPanel.getGraphics());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SplitPane = new javax.swing.JSplitPane();
        TreePanel = new javax.swing.JPanel();
        DrawPanel = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(turna.TURNAApp.class).getContext().getResourceMap(ProjectPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        SplitPane.setName("SplitPane"); // NOI18N

        TreePanel.setBackground(resourceMap.getColor("TreePanel.background")); // NOI18N
        TreePanel.setMinimumSize(new java.awt.Dimension(200, 121));
        TreePanel.setName("TreePanel"); // NOI18N
        TreePanel.setPreferredSize(new java.awt.Dimension(200, 121));

        javax.swing.GroupLayout TreePanelLayout = new javax.swing.GroupLayout(TreePanel);
        TreePanel.setLayout(TreePanelLayout);
        TreePanelLayout.setHorizontalGroup(
            TreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        TreePanelLayout.setVerticalGroup(
            TreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        SplitPane.setLeftComponent(TreePanel);

        DrawPanel.setBackground(resourceMap.getColor("DrawPanel.background")); // NOI18N
        DrawPanel.setAutoscrolls(true);
        DrawPanel.setName("DrawPanel"); // NOI18N
        DrawPanel.setPreferredSize(new java.awt.Dimension(141, 121));
        DrawPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));
        SplitPane.setRightComponent(DrawPanel);

        add(SplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrawPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel TreePanel;
    // End of variables declaration//GEN-END:variables
}
